#!/bin/sh
### BEGIN INIT INFO
# Provides:          pyffd
# Required-Start:    nginx
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: Create dynamic part of /etc/motd
# Description:       /etc/motd is user-editable and static.  This script
#                    creates the initial dynamic part, by default the
#                    output of uname, and stores it in /var/run/motd.dynamic.
#                    Both parts are output by pam_motd.
### END INIT INFO

# and then
# update-rc.d pyffd defaults
# update-rc.d pyffd enable

PATH=/sbin:/usr/sbin:/bin:/usr/bin
BASEDIR="/opt"
ENVDIR="$BASEDIR/django-saml2-idp.env"
APPNAME="pyff"
APPDIR="$BASEDIR/$APPNAME"
LOG_LEVEL="INFO"
METADATA_UPDATE_FREQ=180
PID_PATH="/var/log/uwsgi"
USER=wert
COMMAND="pyffd -p $PID_PATH/$APPNAME.pid -a --loglevel=$LOG_LEVEL --log $PID_PATH/$APPNAME.log --error-log $PID_PATH/$APPNAME.error.log --dir=$APPDIR -H 0.0.0.0 -P 8001 --frequency $METADATA_UPDATE_FREQ --no-caching --proxy $APPDIR/pipelines/md.fd"
STOP_CMD="source $ENVDIR/bin/activate && kill -TERM `cat $APPDIR/pyff.pid`"
RELOAD_CMD="source $ENVDIR/bin/activate && $STOP_CMD; $COMMAND"


mkdir -p $PID_PATH
chown -R $USER $PID_PATH

case "$1" in
  start)
    su -l $USER -c "source $ENVDIR/bin/activate && $COMMAND"
    ;;
  stop)
    #kill -KILL  $(ps ax | grep $APPNAME | awk -F' ' {'print $1'} | xargs echo)
    su -l $USER -c "$STOP_CMD"
    ;;
  restart)
    su -l $USER -c "$RELOAD_CMD"
    ;;
  *)
    echo "Usage: motd [start|stop|restart]" >&2
    exit 1
    ;;
esac

exit 0
